### ISSUE TITLE
Split into yearly components

### ISSUE THREAD

**Issue by AQLT** [jdemetra/jdplus-main#145]
When I right-click on a series, then Split into yearly components, the plot is not rendered. Is this option disabled?

**Comment by a-s-russo** [comment]
This option also does not work for me:

![screenshot](https://github.com/jdemetra/jdplus-main/assets/110582146/2e892917-6b26-4576-896f-c253078dd31c)

**Comment by charphi** [comment]
Fixed in 7ab47ee165a9530fade1f3f9091f7dd2485b5b92

**Comment by a-s-russo** [comment]
Thanks for fixing this @charphi. However, I would like to note the following:

- In version 3.2.1, the 'Split into yearly components' option is available by default when right-clicking on a graph. However, as reported in this issue, clicking on it does not nothing. Note further that if you first select 'Select all' after right-clicking, then select 'Split into yearly components', still nothing happens.
- In version 3.2.2-SNAPSHOT however, when right-clicking on a graph, the option 'Split into yearly components' does not appear. It only appears *after* selecting the 'Select all' option from the context menu. However, why is it necessary to click on 'Select all' to enable the splitting of the graph into yearly components? Shouldn't this option assume by default that 'Select all' has already been chosen? What does 'Select all' even achieve? How can you even select only a portion of the graph rather than all of it?

**Comment by charphi** [comment]
@a-s-russo : I have added a new issue to simplify the usage of these actions. See https://github.com/jdemetra/jdplus-main/issues/247

**Comment by a-s-russo** [comment]
Thanks for this @charphi. Good to see this issue fleshed out in #247.
